notifications:
- to: +1111111111
  from: +2222222222

resorts:
- name: Keystone
  urlBase: keystoneresort.com
  plugin: vail
- name: Vail
  urlBase: vail.com
  plugin: vail
- name: Breckenridge
  urlBase: breckenridge.com
  plugin: vail
- name: Beaver Creek
  urlBase: beavercreek.com
  plugin: vail
- name: Arapahoe Basin 
  urlBase: arapahoebasin.com
  plugin: abasin
- name: Winter Park
  urlBase: winterparkresort.com
  plugin: mtn_powder
  mtn_powder_resort_id: 5
- name: Steamboat
  urlBase: steamboat.com
  plugin: mtn_powder
  mtn_powder_resort_id: 6
- name: Copper
  urlBase: coppercolorado.com
  plugin: copper
- name: Loveland
  urlBase: skiloveland.com
  plugin: loveland