notifications:
- cron: "* * * * *"
  filter: "*"
  sms: +1111111111

resorts:
- name: Keystone
  urlBase: keystoneresort.com
  plugin: vail
- name: Vail
  urlBase: vail.com
  plugin: vail
- name: Breckenridge
  urlBase: breckenridge.com
  plugin: vail
- name: Beaver Creek
  urlBase: beavercreek.com
  plugin: vail
- name: Arapahoe Basin 
  urlBase: arapahoebasin.com
  plugin: abasin
