apiVersion: apps/v1
kind: Deployment
metadata:
  name: trails
  labels:
    app: trails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trails
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: trails
    spec:
      containers:
        - name: trails
          image: trails
          imagePullPolicy: Never
          command:
            - /bin/bash
          args:
            - -c
            - ./trails --server
          env:
            - name: REDIS_ENDPOINT
              value: "none"
