# This is a basic workflow to help you get started with Actions

name: Ski Trails CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure CLI works
        run: |
          pip install -r requirements.txt
          ./trails -o
